# 不使用分号
semi: false
# 使用单引号
singleQuote: true
# 最后一个对象的行尾不要逗号
trailingComma: "none"
# 一个 tab 占 2 个空格的宽度
tabWidth: 2
# 一行最大显示 100 个字符
printWidth: 100
# 在花括号内部插入空格
bracketSpacing: true
# 箭头函数只有一个参数时省略圆括号
arrowParens: "avoid"
